version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend_image:latest
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    deploy:
      replicas: 2
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend_image:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    deploy:
      replicas: 2
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Expose HTTPS port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl  # Mount the SSL certificates
    deploy:
      replicas: 1
    networks:
      - my_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file:
      - ./backend/.env
    networks:
      - my_network

networks:
  my_network:
    external: true
